service: oj-compiler-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 30
  memorySize: 512

functions:
  compiler:
    handler: src/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    environment:
      NODE_ENV: production

plugins:
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - .git/**
    - temp/**