services:
  oj:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URL=${MONGODB_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mongo
    volumes:
      - ./temp:/app/temp

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: