services:
  - type: web
    name: oj-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URL
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: secretKey
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: COMPILER_SERVICE_URL
        value: https://your-compiler-service.amazonaws.com